### ISSUE TITLE
Permission of entrypoint.sh

### ISSUE THREAD

**Issue by Milchdealer** [be-cash/python-ci#1]
https://github.com/be-cash/python-ci/blob/4650bca3890049e3be804bce1556a13b44c89166/Dockerfile#L13

You can set the chmod in your git repository::
https://www.git-scm.com/docs/git-update-index

Saves the extra step ;-)

**Comment by EyeOfPython** [comment]
I franzly rather have it explicit in the Dockerfile and not implicit, but thanks for the headsup :)

**Comment by Milchdealer** [comment]
23 days ago `--chmod` flag for `COPY` was merged into [moby](https://github.com/moby/moby). So if you run the latest docker you could also just use that
